#!/usr/bin/env bash
# script prints 1 to 20; "bad luck from China" the 4th iteration,
# "bad luck from Japan" the 9th iteration,
# "bad luck from Italy" the 17th

current=1
while [ "$current" -le 20 ]
do
    echo "$current"
    case $current in
	4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
    esac
    (( current++ ))
done
