#!/usr/bin/env bash
#Scripts install and activates a firewall to block
#all ports except 22, 80 and 443

sudo apt-get install -y ufw
sudo ufw default deny incoming -y
sudo ufw default allow outgoing -y
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw status
yes | sudo ufw enable
sudo ufw status
